---
title: "Tutorial on food webs"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Tutorial on food webs}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(colSBM)
library(patchwork)
data("foodwebs")
```




```{r}
global_opts = list(nb_cores = 1L,
                   nb_models = 5L,
                   nb_init = 10L,
                   depth = 2L,
                   verbosity = 1, spectral_init = FALSE,
                   Q_max = 8L, plot_details = 1)

set.seed(1234)
res_fw_iid <- estimate_colSBM(netlist = foodwebs[1:3],
                              colsbm_model = "iid", 
                              directed = TRUE,
                              net_id = names(foodwebs)[1:3],
                              nb_run = 1L, 
                              global_opts = global_opts)
```
```{r}
res_fw_iid$BICL
```

```{r}
plot(res_fw_iid$best_fit, type = "graphon", ord = c(3,4,5,2,1))
plot(res_fw_iid$best_fit, type = "meso", mixture = FALSE, ord = c(3,4,5,2,1))
plot(res_fw_iid$best_fit, type = "block", net_id = 1) + 
  plot(res_fw_iid$best_fit, type = "block", net_id = 2) +
  plot(res_fw_iid$best_fit, type = "block", net_id = 3) 
```

