---
title: "Analyse du clustering trouvé en utilisant les complétions CoOPLBM"
output:
    html_document:
        toc: true
        theme: united
---

```{r libraries, echo = FALSE}
devtools::load_all()
```

```{r fonction_pratiques, echo = FALSE}
extract_unlist <- function(data) {
  readRDS(data) |>
    extract_best_bipartite_partition() |>
    unlist()
}

show_groups <- function(collection_list) {
  lapply(collection_list, function(collection) {
    collection$Q
  })
}

partition_BICL <- function(collection_list) {
  sum(sapply(collection_list, function(collection) {
    collection$BICL
  }))
}

extract_collection_clustering_id <- function(collection_list) {
  out_dataframe <- setNames(data.frame(matrix(nrow = 0, ncol = 2)), c("netid", "collection_id"))
  for (col_idx in seq_along(collection_list)) {
    for (net_id in collection_list[[col_idx]]$net_id) {
      out_dataframe[nrow(out_dataframe) + 1, ] <- c(net_id, col_idx)
    }
  }
  out_dataframe
}
```

```{r data_importation, echo = FALSE}
# Uncompleted
uncompleted_iid <- extract_unlist("real_data/data/dore_uncompleted_collection_clustering_nb_run_1_iid_70_networks_08-06-23-16:31:17.Rds")
uncompleted_pi <- extract_unlist("real_data/data/dore_uncompleted_collection_clustering_nb_run_1_pi_70_networks_08-06-23-16:52:16.Rds")
uncompleted_rho <- extract_unlist("real_data/data/dore_uncompleted_collection_clustering_nb_run_1_rho_70_networks_08-06-23-16:49:58.Rds")
uncompleted_pirho <- extract_unlist("real_data/data/dore_uncompleted_collection_clustering_nb_run_1_pirho_70_networks_08-06-23-16:41:33.Rds")

# 0.2 threshold
point_2_iid <- extract_unlist("real_data/data/dore_point_2_completed_collection_clustering_nb_run_1_iid_70_networks_07-06-23-18:40:10.Rds")
point_2_pi <- extract_unlist("real_data/data/dore_point_2_completed_collection_clustering_nb_run_1_pi_70_networks_07-06-23-19:22:19.Rds")
point_2_rho <- extract_unlist("real_data/data/dore_point_2_completed_collection_clustering_nb_run_1_rho_70_networks_07-06-23-20:03:53.Rds")
point_2_pirho <- extract_unlist("real_data/data/dore_point_2_completed_collection_clustering_nb_run_1_pirho_70_networks_07-06-23-21:09:12.Rds")

# 0.5 threshold
point_5_iid <- extract_unlist("real_data/data/dore_point_5_completed_collection_clustering_nb_run_1_iid_70_networks_07-06-23-19:19:53.Rds")
point_5_pi <- extract_unlist("real_data/data/dore_point_5_completed_collection_clustering_nb_run_1_pi_70_networks_07-06-23-21:31:20.Rds")
point_5_rho <- extract_unlist("real_data/data/dore_point_5_completed_collection_clustering_nb_run_1_rho_70_networks_07-06-23-21:03:50.Rds")
point_5_pirho <- extract_unlist("real_data/data/dore_point_5_completed_collection_clustering_nb_run_1_pirho_70_networks_07-06-23-21:13:10.Rds")


# Uniform re-sampled
random_iid <- extract_unlist("real_data/data/dore_random_completed_collection_clustering_nb_run_1_iid_70_networks_07-06-23-21:44:14.Rds")
random_pi <- extract_unlist("real_data/data/dore_random_completed_collection_clustering_nb_run_1_pi_70_networks_07-06-23-22:52:47.Rds")
random_rho <- extract_unlist("real_data/data/dore_random_completed_collection_clustering_nb_run_1_rho_70_networks_08-06-23-18:16:04.Rds")
random_pirho <- extract_unlist("real_data/data/dore_random_completed_collection_clustering_nb_run_1_pirho_70_networks_07-06-23-23:07:08.Rds")
```
