

```{r require_libn, echo = FALSE, include=FALSE}
require("ggplot2")
require("dplyr")
devtools::load_all("R/")
source("wip/temporary_plot.R")
```

```{r load data, echo = FALSE, include = FALSE}
# All results
iid_clustering <- readRDS("simulation/data/dore_collection_clustering_nb_run1_iid_123networks_24-05-23-21:40:42.Rds")

iid_best_partition <- extract_best_bipartite_partition(iid_clustering)
iid_unlist <- unlist(iid_best_partition)

rho_clustering <- readRDS("simulation/data/dore_collection_clustering_nb_run1_rho_123networks_25-05-23-13:58:30.Rds")
rho_best_partition <- extract_best_bipartite_partition(rho_clustering)

pi_clustering <- readRDS("simulation/data/dore_collection_clustering_nb_run1_pi_123networks_25-05-23-17:31:25.Rds")
pi_best_partition <- extract_best_bipartite_partition(pi_clustering)

pirho_clustering <- readRDS("simulation/data/dore_collection_clustering_nb_run1_pirho_123networks_26-05-23-19:22:55.Rds")
pirho_best_partition <- extract_best_bipartite_partition(pirho_clustering)
pirho_unlist <- unlist(pirho_best_partition)
```

## Clustering avec le modèle iid
Avec le modèle *iid* nous obtenons les 5 collections suivantes:
```{r liste_nom, echo = FALSE, results="asis"}
iid_networks_list <- lapply(seq_along(iid_unlist), function(c) {
    length <- length(iid_unlist[[c]]$net_id)
    data.frame(collection_id = rep(c, length), net_id = iid_unlist[[c]]$net_id)
})
for(df_net in iid_networks_list) {
    print(knitr::kable(df_net))
}
```

Une fois le modèle de collection appliqué nous obtenons les structures suivantes:

```{r meso-plot, echo = FALSE, fig.cap = 'Graphiques Méso'}
for(col in iid_unlist) {
    print(plot(col, type = "meso", mixture = TRUE))
}
```