# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

fixed_point_tau <- function(d, tau_m_old_other_dim, Cpi_1_m, Cpi_2_m, pi_m_d, Q_d, n_d_m, nonNAs_m, delta, Calpha, alpha, A_m) {
    .Call('_colSBM_fixed_point_tau', PACKAGE = 'colSBM', d, tau_m_old_other_dim, Cpi_1_m, Cpi_2_m, pi_m_d, Q_d, n_d_m, nonNAs_m, delta, Calpha, alpha, A_m)
}

