

name: render readme

# Controls when the action will run
on:
  push:
    branches: main

jobs:
  render:
    # The type of runner that the job will run on
    runs-on: macOS-latest

    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    - uses: r-lib/actions/setup-r@v2
    - uses: r-lib/actions/setup-pandoc@v2

    # install packages needed
    - name: install required packages
      run: |
        Rscript -e 'install.packages(c("rmarkdown"))'
        Rscript -e 'if (!requireNamespace("remotes", quietly = TRUE)) install.packages("remotes")'
        Rscript -e 'remotes::install_local()'

    # Render READEME.md using rmarkdown
    - name: render README
      run: Rscript -e 'rmarkdown::render("README.Rmd")'

    - name: commit rendered README
      run: |
        git config user.name 'github-actions[bot]'
        git config user.email 'github-actions[bot]@users.noreply.github.com'
        git add README.md
        git add man/figures/README-* || echo "No images to add"
        git commit -m "Re-build README.md" || echo "No changes to commit"
        git push origin main || echo "No changes to commit"
